const countries = [
  // Европа
  {name:"Russian Federation", level:"High", tech:"Cryptography, SOC, Threat Intelligence", rank:5, uni:"MIPT (Phystech)", agency:"NCCCI (National Coordination Centre for Computer Incidents)", lat:55.7558, lng:37.6173},
  {name:"Estonia", level:"Very High", tech:"SOC, Threat Intelligence, Encryption", rank:1, uni:"University of Tartu", agency:"CERT-EE", lat:59.4370, lng:24.7536},
  {name:"United Kingdom", level:"Very High", tech:"Threat Intelligence, SOC, Encryption", rank:2, uni:"University of Oxford", agency:"NCSC", lat:55.3781, lng:-3.4360},
  {name:"Switzerland", level:"High", tech:"SOC, Encryption", rank:3, uni:"ETH Zurich", agency:"MELANI", lat:46.8182, lng:8.2275},
  {name:"Germany", level:"High", tech:"Encryption, SOC, Threat Intelligence", rank:4, uni:"TU Munich", agency:"BSI", lat:51.1657, lng:10.4515},
  {name:"France", level:"High", tech:"SOC, Encryption, Incident Response", rank:5, uni:"École Polytechnique", agency:"ANSSI", lat:46.2276, lng:2.2137},
  {name:"Netherlands", level:"High", tech:"SOC, Encryption, AI Monitoring", rank:6, uni:"Delft University of Technology", agency:"NCSC-NL", lat:52.1326, lng:5.2913},
  {name:"Sweden", level:"High", tech:"SOC, Threat Intelligence", rank:7, uni:"KTH Royal Institute of Technology", agency:"MSB", lat:60.1282, lng:18.6435},
  {name:"Finland", level:"High", tech:"SOC, Encryption", rank:8, uni:"Aalto University", agency:"FICORA", lat:61.9241, lng:25.7482},
  {name:"Italy", level:"High", tech:"SOC, Encryption", rank:9, uni:"Politecnico di Milano", agency:"CNAIPIC", lat:41.8719, lng:12.5674},
  {name:"Spain", level:"High", tech:"SOC, Threat Intelligence", rank:10, uni:"Universidad Politécnica de Madrid", agency:"INCIBE", lat:40.4637, lng:-3.7492},
  {name:"Norway", level:"High", tech:"SOC, Threat Intelligence", rank:11, uni:"NTNU", agency:"NorCERT", lat:60.4720, lng:8.4689},
  {name:"Denmark", level:"High", tech:"SOC, Incident Response", rank:12, uni:"DTU", agency:"Danish CERT", lat:56.2639, lng:9.5018},
  {name:"Austria", level:"High", tech:"SOC, Encryption", rank:13, uni:"TU Wien", agency:"CERT Austria", lat:47.5162, lng:14.5501},
  {name:"Belgium", level:"High", tech:"SOC, Threat Intelligence", rank:14, uni:"KU Leuven", agency:"CERT.be", lat:50.5039, lng:4.4699},
  {name:"Poland", level:"Medium", tech:"SOC, Encryption", rank:15, uni:"Warsaw University of Technology", agency:"CERT Polska", lat:51.9194, lng:19.1451},
  {name:"Czech Republic", level:"Medium", tech:"SOC, Encryption", rank:16, uni:"Czech Technical University", agency:"NÚKIB", lat:49.8175, lng:15.4730},
  {name:"Portugal", level:"Medium", tech:"SOC, Threat Intelligence", rank:17, uni:"University of Lisbon", agency:"CNCS", lat:39.3999, lng:-8.2245},
  {name:"Greece", level:"Medium", tech:"SOC, Threat Intelligence", rank:18, uni:"National Technical University of Athens", agency:"CSIRT-GR", lat:39.0742, lng:21.8243},
  {name:"Hungary", level:"Medium", tech:"SOC, Encryption", rank:19, uni:"Budapest University of Technology", agency:"NKI", lat:47.1625, lng:19.5033},
  {name:"Turkey", level:"Medium", tech:"SOC, Government CERT", rank:20, uni:"METU", agency:"USOM", lat:39.9334, lng:32.8597},
  {name:"Slovakia", level:"Medium", tech:"SOC, Encryption", rank:21, uni:"Slovak University of Technology", agency:"SK-CERT", lat:48.6690, lng:19.6990},
  {name:"Kazakhstan", level:"Medium", tech:"SOC, Government CERT", rank:22, uni:"KazNU", agency:"CERT-KZ", lat:48.0196, lng:66.9237},
  {name:"Lithuania", level:"Medium", tech:"SOC, Threat Intelligence", rank:23, uni:"Vilnius University", agency:"CERT-LT", lat:55.1694, lng:23.8813},
  {name:"Latvia", level:"Medium", tech:"SOC, Threat Intelligence", rank:24, uni:"University of Latvia", agency:"CERT-LV", lat:56.8796, lng:24.6032},
  {name:"Uzbekistan", level:"Medium", tech:"SOC, Basic Threat Monitoring", rank:25, uni:"TUIT", agency:"UZCERT", lat:41.3775, lng:64.5853},
  {name:"Ukraine", level:"Medium", tech:"SOC, Threat Intelligence", rank:26, uni:"KPI Kyiv", agency:"CERT-UA", lat:48.3794, lng:31.1656},
  {name:"Belarus", level:"Medium", tech:"SOC, Encryption", rank:27, uni:"BSU", agency:"CERT-BY", lat:53.9006, lng:27.5590},
  {name:"Romania", level:"Medium", tech:"SOC, Threat Intelligence", rank:28, uni:"University Politehnica of Bucharest", agency:"CERT-RO", lat:45.9432, lng:24.9668},
  {name:"Bulgaria", level:"Medium", tech:"SOC, Basic Encryption", rank:29, uni:"Sofia University", agency:"CERT-BG", lat:42.7339, lng:25.4858},
  {name:"Kyrgyzstan", level:"Low", tech:"Basic SOC", rank:30, uni:"KNU", agency:"CERT-KG", lat:41.2044, lng:74.7661},
  {name:"Georgia", level:"Low", tech:"Basic SOC", rank:31, uni:"TSU", agency:"CERT-GE", lat:42.3154, lng:43.3569},
  {name:"Armenia", level:"Low", tech:"Basic SOC", rank:32, uni:"Yerevan State University", agency:"CERT-AM", lat:40.1792, lng:44.4991},
  {name:"Azerbaijan", level:"Low", tech:"Basic SOC", rank:33, uni:"ADA University", agency:"CERT-AZ", lat:40.1431, lng:47.5769},
  {name:"Montenegro", level:"Low", tech:"Basic SOC", rank:34, uni:"University of Montenegro", agency:"CERT-ME", lat:42.4410, lng:19.2620},
  {name:"North Macedonia", level:"Low", tech:"Basic SOC", rank:35, uni:"Ss. Cyril and Methodius University", agency:"CERT-MK", lat:41.6086, lng:21.7453},
  {name:"Serbia", level:"Low", tech:"Basic SOC", rank:36, uni:"University of Belgrade", agency:"CERT-RS", lat:44.8176, lng:20.4569},
  {name:"Bosnia and Herzegovina", level:"Low", tech:"Basic SOC", rank:37, uni:"University of Sarajevo", agency:"CERT-BA", lat:43.9159, lng:17.6791},
  {name:"Albania", level:"Low", tech:"Basic SOC", rank:38, uni:"University of Tirana", agency:"CERT-AL", lat:41.1533, lng:20.1683},
  {name:"Malta", level:"Medium", tech:"SOC, Threat Monitoring", rank:39, uni:"University of Malta", agency:"MT-CERT", lat:35.9375, lng:14.3754},
  {name:"Cyprus", level:"Medium", tech:"SOC, Threat Monitoring", rank:40, uni:"University of Cyprus", agency:"CY-CERT", lat:35.1264, lng:33.4299},
  {name:"Liechtenstein", level:"Medium", tech:"Basic SOC", rank:41, uni:"University of Liechtenstein", agency:"LI-CERT", lat:47.1660, lng:9.5554},
  {name:"Monaco", level:"High", tech:"SOC, Encryption", rank:42, uni:"Monaco University", agency:"MC-CERT", lat:43.7384, lng:7.4246},
  {name:"Andorra", level:"Low", tech:"Basic SOC", rank:43, uni:"University of Andorra", agency:"AD-CERT", lat:42.5063, lng:1.5218},
  {name:"San Marino", level:"Low", tech:"Basic SOC", rank:44, uni:"University of San Marino", agency:"SM-CERT", lat:43.9336, lng:12.4578},
  {name:"Vatican City", level:"Low", tech:"Basic SOC", rank:45, uni:"Pontifical University", agency:"VA-CERT", lat:41.9029, lng:12.4534},

  // Азия
  {name:"Israel", level:"Very High", tech:"SOC, AI Security, Encryption", rank:1, uni:"Technion", agency:"ISOC", lat:31.0461, lng:34.8516},
  {name:"Singapore", level:"Very High", tech:"SOC, AI Security, Threat Intelligence", rank:2, uni:"NUS", agency:"CSA Singapore", lat:1.3521, lng:103.8198},
  {name:"Japan", level:"High", tech:"Incident Response, AI Monitoring", rank:3, uni:"University of Tokyo", agency:"NISC", lat:36.2048, lng:138.2529},
  {name:"South Korea", level:"High", tech:"SOC, Threat Intelligence", rank:4, uni:"KAIST", agency:"KISA", lat:35.9078, lng:127.7669},
  {name:"China", level:"High", tech:"SOC, Threat Intelligence, AI Monitoring", rank:5, uni:"Tsinghua University", agency:"CNCERT", lat:35.8617, lng:104.1954},
  {name:"India", level:"Medium", tech:"SOC, Encryption", rank:6, uni:"IIT Delhi", agency:"CERT-IN", lat:20.5937, lng:78.9629},
  {name:"United Arab Emirates", level:"Medium", tech:"SOC, Threat Intelligence", rank:7, uni:"Khalifa University", agency:"aeCERT", lat:23.4241, lng:53.8478},
  {name:"Qatar", level:"Medium", tech:"SOC, Threat Monitoring", rank:8, uni:"Qatar University", agency:"Q-CERT", lat:25.3548, lng:51.1839},
  {name:"Malaysia", level:"Medium", tech:"SOC, Encryption", rank:9, uni:"UTM", agency:"MyCERT", lat:4.2105, lng:101.9758},
  {name:"Saudi Arabia", level:"Medium", tech:"SOC, Threat Intelligence", rank:10, uni:"King Saud University", agency:"SaudiCERT", lat:23.8859, lng:45.0792},
  {name:"Kazakhstan", level:"Medium", tech:"SOC, Government CERT", rank:11, uni:"KazNU", agency:"CERT-KZ", lat:48.0196, lng:66.9237},
  {name:"Uzbekistan", level:"Medium", tech:"SOC, Basic Threat Monitoring", rank:12, uni:"TUIT", agency:"UZCERT", lat:41.3775, lng:64.5853},
  {name:"Kyrgyz Republic", level:"Low", tech:"Basic SOC", rank:13, uni:"KNU", agency:"CERT-KG", lat:41.2044, lng:74.7661},
  {name:"Tajikistan", level:"Low", tech:"Basic SOC", rank:14, uni:"Tajik National University", agency:"CERT-TJ", lat:38.8610, lng:71.2761},
  {name:"Bangladesh", level:"Low", tech:"SOC, Threat Monitoring", rank:15, uni:"BUET", agency:"Bangladesh-CERT", lat:23.6850, lng:90.3563},
  {name:"Pakistan", level:"Low", tech:"SOC, Basic Threat Monitoring", rank:16, uni:"NUST", agency:"PK-CERT", lat:30.3753, lng:69.3451},
  {name:"Nepal", level:"Low", tech:"Basic SOC", rank:17, uni:"Tribhuvan University", agency:"NP-CERT", lat:28.3949, lng:84.1240},
  {name:"Bhutan", level:"Low", tech:"Basic SOC", rank:18, uni:"Royal University of Bhutan", agency:"BT-CERT", lat:27.5142, lng:90.4336},
  {name:"Sri Lanka", level:"Low", tech:"SOC, Threat Monitoring", rank:19, uni:"University of Colombo", agency:"LK-CERT", lat:7.8731, lng:80.7718},

  // Северная Америка
  {name:"United States", level:"Very High", tech:"Zero Trust, AI SOC, Encryption", rank:1, uni:"Carnegie Mellon University", agency:"CISA", lat:37.0902, lng:-95.7129},
  {name:"Canada", level:"High", tech:"SOC, Encryption, Threat Intelligence", rank:2, uni:"University of Toronto", agency:"CCCS", lat:56.1304, lng:-106.3468},
  {name:"Mexico", level:"Medium", tech:"SOC, Threat Monitoring", rank:20, uni:"UNAM", agency:"CERT-MX", lat:23.6345, lng:-102.5528},

  // Южная Америка
  {name:"Brazil", level:"Medium", tech:"SOC, Threat Intelligence", rank:15, uni:"University of São Paulo", agency:"CTIR Gov BR", lat:-14.2350, lng:-51.9253},
  {name:"Argentina", level:"Medium", tech:"SOC, Threat Monitoring", rank:18, uni:"University of Buenos Aires", agency:"CERT-AR", lat:-38.4161, lng:-63.6167},
  {name:"Chile", level:"Medium", tech:"SOC, Threat Monitoring", rank:19, uni:"Pontificia Universidad Católica de Chile", agency:"CSIRT-CL", lat:-35.6751, lng:-71.5430},
  {name:"Colombia", level:"Medium", tech:"SOC, Threat Monitoring", rank:22, uni:"Universidad de los Andes", agency:"CSIRT-CO", lat:4.5709, lng:-74.2973},
  {name:"Peru", level:"Low", tech:"Basic SOC", rank:28, uni:"Pontificia Universidad Católica del Perú", agency:"CSIRT-PE", lat:-9.1900, lng:-75.0152},
  {name:"Venezuela", level:"Low", tech:"Basic SOC", rank:30, uni:"Central University of Venezuela", agency:"CERT-VE", lat:6.4238, lng:-66.5897},
  {name:"Ecuador", level:"Low", tech:"Basic SOC", rank:72, uni:"Pontificia Universidad Católica del Ecuador", agency:"EC-CERT", lat:-1.8312, lng:-78.1834},
  {name:"Bolivia", level:"Low", tech:"Basic SOC", rank:73, uni:"Universidad Mayor de San Andrés", agency:"BO-CERT", lat:-16.2902, lng:-63.5887},
  {name:"Paraguay", level:"Low", tech:"Basic SOC", rank:74, uni:"National University of Asunción", agency:"PY-CERT", lat:-23.4425, lng:-58.4438},
  {name:"Uruguay", level:"Low", tech:"Basic SOC", rank:75, uni:"University of the Republic", agency:"UY-CERT", lat:-32.5228, lng:-55.7658},
  {name:"Guyana", level:"Low", tech:"Basic SOC", rank:76, uni:"University of Guyana", agency:"GY-CERT", lat:4.8604, lng:-58.9302},
  {name:"Suriname", level:"Low", tech:"Basic SOC", rank:77, uni:"Anton de Kom University", agency:"SR-CERT", lat:3.9193, lng:-56.0278},

   // Африка
  {name:"Kenya", level:"Low", tech:"Basic SOC", rank:36, uni:"University of Nairobi", agency:"KE-CERT", lat:-0.0236, lng:37.9062},
  {name:"Morocco", level:"Low", tech:"Basic SOC", rank:37, uni:"Mohammed V University", agency:"MA-CERT", lat:31.7917, lng:-7.0926},
  {name:"Algeria", level:"Low", tech:"Basic SOC", rank:38, uni:"University of Algiers", agency:"DZ-CERT", lat:28.0339, lng:1.6596},
  {name:"Ethiopia", level:"Low", tech:"Basic SOC", rank:39, uni:"Addis Ababa University", agency:"ET-CERT", lat:9.1450, lng:40.4897},
  {name:"Tanzania", level:"Low", tech:"Basic SOC", rank:40, uni:"University of Dar es Salaam", agency:"TZ-CERT", lat:-6.3690, lng:34.8888},
  {name:"Uganda", level:"Low", tech:"Basic SOC", rank:41, uni:"Makerere University", agency:"UG-CERT", lat:1.3733, lng:32.2903},
  {name:"Ghana", level:"Low", tech:"Basic SOC", rank:42, uni:"University of Ghana", agency:"GH-CERT", lat:7.9465, lng:-1.0232},
  {name:"Cameroon", level:"Low", tech:"Basic SOC", rank:43, uni:"University of Yaoundé", agency:"CM-CERT", lat:7.3697, lng:12.3547},
  {name:"Ivory Coast", level:"Low", tech:"Basic SOC", rank:44, uni:"Université Félix Houphouët-Boigny", agency:"CI-CERT", lat:7.539989, lng:-5.5471},
  {name:"Senegal", level:"Low", tech:"Basic SOC", rank:45, uni:"Cheikh Anta Diop University", agency:"SN-CERT", lat:14.4974, lng:-14.4524},
  {name:"Libya", level:"Low", tech:"Basic SOC", rank:46, uni:"University of Tripoli", agency:"LY-CERT", lat:26.3351, lng:17.2283},
  {name:"Tunisia", level:"Low", tech:"Basic SOC", rank:47, uni:"University of Tunis", agency:"TN-CERT", lat:33.8869, lng:9.5375},
  {name:"Angola", level:"Low", tech:"Basic SOC", rank:48, uni:"Agostinho Neto University", agency:"AO-CERT", lat:-11.2027, lng:17.8739},
  {name:"Eritrea", level:"Low", tech:"Basic SOC", rank:49, uni:"Asmara University", agency:"ER-CERT", lat:15.1794, lng:39.7823},
  {name:"Sudan", level:"Low", tech:"Basic SOC", rank:50, uni:"University of Khartoum", agency:"SD-CERT", lat:12.8628, lng:30.2176},

  // Океания
  {name:"Australia", level:"Very High", tech:"SOC, Encryption, Threat Intelligence", rank:1, uni:"University of Sydney", agency:"ACSC", lat:-25.2744, lng:133.7751},
  {name:"New Zealand", level:"High", tech:"SOC, Encryption", rank:2, uni:"University of Auckland", agency:"CERT-NZ", lat:-40.9006, lng:174.8860},
  {name:"Fiji", level:"Low", tech:"Basic SOC", rank:51, uni:"University of the South Pacific", agency:"FJ-CERT", lat:-17.7134, lng:178.0650},
  {name:"Papua New Guinea", level:"Low", tech:"Basic SOC", rank:52, uni:"University of Papua New Guinea", agency:"PG-CERT", lat:-6.3149, lng:143.9555},
  {name:"Samoa", level:"Low", tech:"Basic SOC", rank:53, uni:"National University of Samoa", agency:"WS-CERT", lat:-13.7590, lng:-172.1046},
  {name:"Tonga", level:"Low", tech:"Basic SOC", rank:54, uni:"Kingdom of Tonga University", agency:"TO-CERT", lat:-21.1789, lng:-175.1982},
  {name:"Vanuatu", level:"Low", tech:"Basic SOC", rank:55, uni:"University of Vanuatu", agency:"VU-CERT", lat:-15.3767, lng:166.9592},
  {name:"Solomon Islands", level:"Low", tech:"Basic SOC", rank:56, uni:"Solomon Islands National University", agency:"SB-CERT", lat:-9.6457, lng:160.1562},
  {name:"Micronesia", level:"Low", tech:"Basic SOC", rank:57, uni:"College of Micronesia", agency:"FM-CERT", lat:7.4256, lng:150.5508},

  // Мелкие острова и карибский регион
  {name:"Cuba", level:"Low", tech:"Basic SOC", rank:58, uni:"University of Havana", agency:"CU-CERT", lat:21.5218, lng:-77.7812},
  {name:"Jamaica", level:"Low", tech:"Basic SOC", rank:59, uni:"University of the West Indies", agency:"JM-CERT", lat:18.1096, lng:-77.2975},
  {name:"Bahamas", level:"Low", tech:"Basic SOC", rank:60, uni:"University of the Bahamas", agency:"BS-CERT", lat:25.0343, lng:-77.3963},
  {name:"Haiti", level:"Low", tech:"Basic SOC", rank:61, uni:"Quisqueya University", agency:"HT-CERT", lat:18.9712, lng:-72.2852},
  {name:"Dominican Republic", level:"Low", tech:"Basic SOC", rank:62, uni:"Pontificia Universidad Católica Madre y Maestra", agency:"DO-CERT", lat:18.7357, lng:-70.1627},
  {name:"Puerto Rico", level:"Low", tech:"Basic SOC", rank:63, uni:"University of Puerto Rico", agency:"PR-CERT", lat:18.2208, lng:-66.5901}
];

